-- Q0.1 Row counts in every table the scrapers write to
select 'medicines' as table_name, count(*) as rows from medicines
union all select 'pharmacies', count(*) from pharmacies
union all select 'cdsco_reference', count(*) from cdsco_reference
union all select 'drug_alerts', count(*) from drug_alerts
union all select 'etl_failed_rows', count(*) from etl_failed_rows;

-- Q0.2 Medicines by where they came from (manual = project sample data, not scraped)
select source, count(*) as rows, max(updated_at) as last_loaded
from medicines group by source order by source;

-- Q1.1 CDSCO registry: size
select count(*) as registry_rows,
       count(distinct firm_name_normalized) as distinct_firms
from cdsco_reference;

-- Q1.2 CDSCO registry: sample rows
select brand_name, firm_name from cdsco_reference order by id limit 10;

-- Q1.3 CDSCO registry: search a brand
select brand_name, firm_name from cdsco_reference where brand_name ilike '%dolo%' limit 10;

-- Q1.4 CDSCO registry: firm_name holding an address instead of a company (data-quality issue)
select count(*) filter (where firm_name ~ '[0-9]' and firm_name like '%,%') as looks_like_address,
       count(*) filter (where not (firm_name ~ '[0-9]' and firm_name like '%,%')) as looks_like_company
from cdsco_reference;

-- Q2.1 CDSCO recall alerts: empty because the AI extraction step needs a Gemini/Groq key
select count(*) as alert_rows from drug_alerts;

-- Q3.1 Jan Aushadhi products: what arrived
select generic_name, strength, dosage_form, schedule, mrp, jan_aushadhi_price, manufacturer
from medicines where source = 'janaushadhi' order by generic_name;

-- Q3.2 Jan Aushadhi products: fields parsed from raw names
select count(*) as rows,
       count(strength) as with_strength,
       count(dosage_form) as with_dosage_form,
       min(mrp) as cheapest_mrp, max(mrp) as costliest_mrp
from medicines where source = 'janaushadhi';

-- Q4.1 Jan Aushadhi Kendras: shops with map coordinates (no contact names or phones)
select split_part(name, ' - ', 1) as kendra_code, district, state,
       round(st_y(location::geometry)::numeric, 4) as latitude,
       round(st_x(location::geometry)::numeric, 4) as longitude
from pharmacies where name like 'PMBJK%'
order by kendra_code, created_at limit 10;

-- Q4.2 Jan Aushadhi Kendras: coverage by state
select state, count(distinct split_part(name, ' - ', 1)) as unique_kendras, count(*) as rows
from pharmacies where name like 'PMBJK%' group by state order by state;

-- Q4.3 Jan Aushadhi Kendras: duplicates created by re-running (known bug)
select split_part(name, ' - ', 1) as kendra_code, count(*) as copies
from pharmacies where name like 'PMBJK%'
group by 1 having count(*) > 1 order by 1;

-- Q4.4 Jan Aushadhi Kendras: nearest scraped shops to a point (PostGIS works on the scraped data)
select kendra_code, district,
       round((st_distance(location, st_setsrid(st_makepoint(78.48, 13.55), 4326)::geography) / 1000)::numeric, 1) as km_away
from (select distinct on (split_part(name, ' - ', 1)) split_part(name, ' - ', 1) as kendra_code, district, location
      from pharmacies where name like 'PMBJK%') as kendras
order by km_away limit 5;

-- Q5.1 Commercial dataset: what arrived
select brand_name, generic_name, manufacturer, composition, dosage_form, mrp
from medicines where source = 'commercial' order by brand_name;

-- Q5.2 Commercial dataset: barcodes are generated by the scraper, not real pack barcodes
select brand_name, barcode_id, left(barcode_id, 3) as prefix
from medicines where source = 'commercial' order by brand_name limit 10;

-- Q6.1 CDSCO validation result per scraped medicine
select coalesce(brand_name, generic_name) as medicine, source,
       is_cdsco_verified, round(cdsco_match_score::numeric, 1) as match_score,
       matched_cdsco_product, matched_cdsco_manufacturer
from medicines where source in ('janaushadhi', 'commercial')
order by match_score desc nulls last;

-- Q6.2 CDSCO validation summary
select source, count(*) as rows, count(*) filter (where is_cdsco_verified) as verified,
       round(avg(cdsco_match_score)::numeric, 1) as avg_match_score
from medicines where source in ('janaushadhi', 'commercial') group by source;

-- Q7.1 Load health: rows that failed to load (should be 0)
select pipeline_name, source_table, error_category, count(*)
from etl_failed_rows group by 1, 2, 3;

-- Q7.2 Scraped data is usable by the app: the same search the scan page uses
select brand_name, generic_name, mrp, round(similarity::numeric, 2) as similarity
from search_medicines_text('allegra', 5);
